### ISSUE TITLE
Node 8 End LTS 31-Dec-19

### ISSUE THREAD

**Issue by kreig303** [Hollywood/remove-outside-collaborators#21]
Node 8 LTS support ends [at the end of 2019](https://github.com/nodejs/Release).

We should update the `.travis.yml` to acknowledge this (at a minimum).

Currently it's only checking against Node 8.6.0.

**Comment by kreig303** [comment]
Leaving this open post-merge in case there are lingering effects.

**Comment by Hollywood** [comment]
Thanks a ton @kreig303
